### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by sfhelmet** [sfhelmet/Converter#10]
## Description
Both Prolog and PlantUML can have alias, make a linear transformation of it

## Tasks:
- [ ] Parse aliases in PlantUML
- [ ] Linear Conversion to Prolog
- [ ] Linear Conversion to PlantUML

## Notes
